### PR TITLE
Attempt to keep line length legible and below 80 characters with small e...

### PR DESCRIPTION
**Pull request by eshim**
...xceptions.

### CODE REVIEW

**Comment by matt-ward** [comment]
I think they're okay on the comments...come on.

**Comment by eshim** [comment]
Ah, I'll see what I can do about the docstring lengths.

**Comment by wglodek** [comment]
@eshim We agree with @matt-ward that the pull request does not have enough substance.

**Comment by eshim** [comment]
I understand, I'll approach this again when have more time to cover
formatting.

**Pull request closed without merging**
