### PR TITLE
Remove the dependence on PyCrypto

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by xmunoz** [comment]
Shouldn't the [readme](https://github.com/USArmyResearchLab/Dshell#prerequisites) also be changed as part of this PR?

**Comment by alex** [comment]
Good catch. Done.

**Comment by curtiszimmerman** [comment]
Also there is a PyCrypto reference in `install-ubuntu.sh`. :)

**Comment by wglodek** [comment]
The file bin/pcapanon.py uses PyCrypto.  We are in the process of getting additional modules approved for public release that utilize this library.

**Comment by alex** [comment]
@wglodek I'm not sure I understand, right now everything this file uses PyCrypto for is provided by the standard library.

**Pull request closed without merging**
