### PR TITLE
ElasticSearch Output module

### PR DESCRIPTION
**Pull request by amm3**
This is a new output module for elasticsearch.  It works standalone with `--output elasticout,host=ES_HOST,index=INDEXNAME`, but I find it also useful to extend the class.  This allows for more centralized control over the cluster and dynamic/deterministic index names and doc IDs.

### CODE REVIEW

**Comment by dev195** [comment]
Do you think you can have doc_type defined as a kwarg, too? It'd feel more consistent than having it be the only one that needs to be defined in the decoder.

**Comment by amm3** [comment]
Sure thing.  It currently uses the *name* of the decoder by default (provided it's in the kwargs passed to alert), so the decoder doesn't have to *do* anything different/specific.  But I think it **absolutely** makes sense to allow override of this with command line args.

**Comment by dev195** [comment]
Okay, looks good. Since it does use the third-party elasticsearch library, I'll update the Dshell README to mention this.

**Comment by amm3** [comment]
Thanks.  Good call.

**Pull request merged**
