### PR TITLE
First partial Pylint sweep of decode.py

### PR DESCRIPTION
**Pull request by kstrauser**
I'd love to work on this project, but the code formatting is very un-Pythonic and difficult to read. While Python doesn't enforce a particular formatting style (`foo = 'bar'` and `foo='bar'` both work), it has well-defined and widely accepted community standards for such things. Most Python developers expect code to look a certain way and may be turned off from contributing if this project's code doesn't meet those expectations.

Please consider using tools like [Pylint](http://www.pylint.org) and [flake8](https://pypi.python.org/pypi/flake8) to suggest ways you can make this code base more Pythonic. Since you don't actually have to include any of those packages' code in this repo, you don't need to worry about redistribution licensing; just download, use them, and follow their advice.

I don't necessarily suggest that you merge this pull request as-is, and you won't hurt my feelings if you reject it. I mainly mean it as an example of what the same code might look like with more standard formatting.

PS: Go Navy.

### CODE REVIEW

**Comment by mathisonian** [comment]
:+1:

**Comment by curtiszimmerman** [comment]
To be perfectly honest, I don't think the Army is too worried about hurting your feelings. :)

**Comment by RyPeck** [comment]
:+1: For the use of PyLint and looking to conform to PEP8.

**Comment by wglodek** [comment]
@kstrauser Thank you for taking the time to run PyLint on decode.py.  We will be going through each file to make sure it conforms to the PEP8 standard.

**Pull request merged**
